# Generated by Django 4.0.3 on 2022-03-21 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/images')),
                ('image_names', models.CharField(max_length=200)),
                ('image_slug', models.CharField(max_length=200)),
                ('image_caption', models.CharField(max_length=2000)),
                ('likes', models.IntegerField()),
                ('comments', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
